### ISSUE TITLE
Error while installing pymle

### ISSUE THREAD

**Issue by gorodskayafialka** [jkirkby3/pymle#2]
Hello,

I've tried installing your package using "pip install git+https://github.com/jkirkby3/pymle.git" but I got this error: "error: package directory 'ctmc' does not exist". Could you please explain how to get rid of that error?

Thank you in advance

**Comment by gorodskayafialka** [comment]
Resolved this issue by cloning git and changing this line in setup.py

packages=find_packages(where="pymle"),

to 

packages=find_packages(),

**Comment by jkirkby3** [comment]
Thank you! I will make this change to the repo
